jobs:
 - template: default.yml@templates
   parameters:
     codecov_token: $(CODECOV_TOKEN_SECRET)
     minrust: 1.48.0 # nom 7
     env:
       RUST_BACKTRACE: 1
     setup:
      - checkout: self
        submodules: recursive
 - job: features
   displayName: "Check feature combinations"
   pool:
     vmImage: ubuntu-latest
   steps:
     - template: install-rust.yml@templates
       parameters:
         rust: stable
     - script: cargo install cargo-hack
       displayName: install cargo-hack
     - script: cargo hack --feature-powerset check --all-targets
       displayName: cargo hack

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.4
      endpoint: jonhoo
